# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('INTERNATIONAL', 'International (Org-wide)'), ('PROVINCIAL', 'Provincial'), ('LOCAL', 'Local (Church)')], db_index=True, default='LOCAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue_name', models.CharField(blank=True, default='', max_length=255)),
                ('venue_address', models.TextField(blank=True, default='')),
                ('is_online', models.BooleanField(default=False)),
                ('stream_url', models.URLField(blank=True, default='')),
                ('max_attendance', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finance_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
