# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='church',
            field=models.ForeignKey(blank=True, help_text='Populated only for LOCAL events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.church'),
        ),
    ]
