# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Populated for PROVINCIAL and LOCAL events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.province'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'scope', 'status'], name='events_even_organiz_804630_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='events_even_start_d_e338a8_idx'),
        ),
    ]
