# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='The Arch Bishop responsible for this region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='province',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='The Bishop responsible for this province.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_provinces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='province',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='organizations.region'),
        ),
        migrations.AddField(
            model_name='church',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Primary Church Admin / Pastor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_churches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='church',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='organizations.province'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='church',
            unique_together={('organization', 'name')},
        ),
    ]
