# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_type', models.CharField(choices=[('HOME_GROUP', 'Home Group'), ('TASKFORCE', 'Taskforce'), ('WORSHIP_TEAM', 'Worship Team'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('meeting_day', models.CharField(blank=True, default='', max_length=20)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_location', models.TextField(blank=True, default='')),
                ('meeting_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Church Group',
                'verbose_name_plural': 'Church Groups',
                'ordering': ['church', 'group_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined', models.DateField(auto_now_add=True)),
                ('is_co_leader', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.churchgroup')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
            },
        ),
    ]
