# Generated by Django 4.2.30 on 2026-04-20 22:40

from django.db import migrations, models
import onboarding.models.invitation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='The email address the invitation is sent to.', max_length=254)),
                ('role_proffered', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('APOSTLE', 'Apostle'), ('ARCH_BISHOP', 'Arch Bishop'), ('BISHOP', 'Bishop'), ('CHURCH_ADMIN', 'Church Admin'), ('PASTOR', 'Pastor'), ('MINISTER', 'Minister'), ('ELDER', 'Elder'), ('DEACON', 'Deacon'), ('MEMBER', 'Member')], help_text='The role the invitee will assume on acceptance.', max_length=30)),
                ('target_entity_id', models.UUIDField(blank=True, help_text='UUID of the Region / Province / Church the invitee joins. Null for organization-wide roles (SUPER_ADMIN, APOSTLE).', null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(default=onboarding.models.invitation._default_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
